// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_multisig
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-06-06, STEPS: `100`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Native), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 512
//! HOSTNAME: `trinity`, CPU: `AMD Ryzen 9 7950X 16-Core Processor`

// Executed Command:
// ./target/release/polymesh-private
// benchmark
// pallet
// -s
// 100
// -r
// 5
// -p=pallet_multisig
// -e=*
// --heap-pages
// 4096
// --db-cache
// 512
// --execution
// native
// --output
// ./pallets/weights/src/
// --template
// ./.maintain/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use polymesh_runtime_common::{RocksDbWeight as DbWeight, Weight};

/// Weights for pallet_multisig using the Substrate node and recommended hardware.
pub struct SubstrateWeight;
impl pallet_multisig::WeightInfo for SubstrateWeight {
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigNonce (r:1 w:1)
    // Proof Skipped: MultiSig MultiSigNonce (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity NumberOfGivenAuths (r:1 w:1)
    // Proof Skipped: Identity NumberOfGivenAuths (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CurrentAuthId (r:1 w:1)
    // Proof Skipped: Identity CurrentAuthId (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity AuthorizationsGiven (r:0 w:256)
    // Proof Skipped: Identity AuthorizationsGiven (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity Authorizations (r:0 w:256)
    // Proof Skipped: Identity Authorizations (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:0 w:1)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSignsRequired (r:0 w:1)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    /// The range of component `i` is `[1, 256]`.
    fn create_multisig(i: u32) -> Weight {
        // Minimum execution time: 18_083 nanoseconds.
        Weight::from_ref_time(8_510_547)
            // Standard Error: 12_131
            .saturating_add(Weight::from_ref_time(3_667_192).saturating_mul(i.into()))
            .saturating_add(DbWeight::get().reads(5))
            .saturating_add(DbWeight::get().writes(5))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(i.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig ProposalIds (r:1 w:1)
    // Proof Skipped: MultiSig ProposalIds (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSigners (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigTxDone (r:1 w:1)
    // Proof Skipped: MultiSig MultiSigTxDone (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Votes (r:1 w:1)
    // Proof Skipped: MultiSig Votes (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: MultiSig ProposalDetail (r:0 w:1)
    // Proof Skipped: MultiSig ProposalDetail (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Proposals (r:0 w:1)
    // Proof Skipped: MultiSig Proposals (max_values: None, max_size: None, mode: Measured)
    fn create_or_approve_proposal_as_identity() -> Weight {
        // Minimum execution time: 30_477 nanoseconds.
        Weight::from_ref_time(31_168_000)
            .saturating_add(DbWeight::get().reads(10))
            .saturating_add(DbWeight::get().writes(7))
    }
    // Storage: MultiSig ProposalIds (r:1 w:1)
    // Proof Skipped: MultiSig ProposalIds (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSigners (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigTxDone (r:1 w:1)
    // Proof Skipped: MultiSig MultiSigTxDone (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Votes (r:1 w:1)
    // Proof Skipped: MultiSig Votes (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: MultiSig ProposalDetail (r:0 w:1)
    // Proof Skipped: MultiSig ProposalDetail (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Proposals (r:0 w:1)
    // Proof Skipped: MultiSig Proposals (max_values: None, max_size: None, mode: Measured)
    fn create_or_approve_proposal_as_key() -> Weight {
        // Minimum execution time: 31_980 nanoseconds.
        Weight::from_ref_time(32_771_000)
            .saturating_add(DbWeight::get().reads(11))
            .saturating_add(DbWeight::get().writes(7))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSigners (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigTxDone (r:1 w:1)
    // Proof Skipped: MultiSig MultiSigTxDone (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Votes (r:1 w:1)
    // Proof Skipped: MultiSig Votes (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: MultiSig ProposalDetail (r:0 w:1)
    // Proof Skipped: MultiSig ProposalDetail (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Proposals (r:0 w:1)
    // Proof Skipped: MultiSig Proposals (max_values: None, max_size: None, mode: Measured)
    fn create_proposal_as_identity() -> Weight {
        // Minimum execution time: 29_294 nanoseconds.
        Weight::from_ref_time(29_896_000)
            .saturating_add(DbWeight::get().reads(9))
            .saturating_add(DbWeight::get().writes(6))
    }
    // Storage: MultiSig MultiSigSigners (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigTxDone (r:1 w:1)
    // Proof Skipped: MultiSig MultiSigTxDone (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Votes (r:1 w:1)
    // Proof Skipped: MultiSig Votes (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: MultiSig ProposalDetail (r:0 w:1)
    // Proof Skipped: MultiSig ProposalDetail (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Proposals (r:0 w:1)
    // Proof Skipped: MultiSig Proposals (max_values: None, max_size: None, mode: Measured)
    fn create_proposal_as_key() -> Weight {
        // Minimum execution time: 30_588 nanoseconds.
        Weight::from_ref_time(30_847_000)
            .saturating_add(DbWeight::get().reads(10))
            .saturating_add(DbWeight::get().writes(6))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSigners (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Votes (r:1 w:1)
    // Proof Skipped: MultiSig Votes (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Proposals (r:1 w:0)
    // Proof Skipped: MultiSig Proposals (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig ProposalDetail (r:1 w:1)
    // Proof Skipped: MultiSig ProposalDetail (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    fn approve_as_identity() -> Weight {
        // Minimum execution time: 28_043 nanoseconds.
        Weight::from_ref_time(28_613_000)
            .saturating_add(DbWeight::get().reads(9))
            .saturating_add(DbWeight::get().writes(4))
    }
    // Storage: MultiSig MultiSigSigners (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Votes (r:1 w:1)
    // Proof Skipped: MultiSig Votes (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Proposals (r:1 w:0)
    // Proof Skipped: MultiSig Proposals (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig ProposalDetail (r:1 w:1)
    // Proof Skipped: MultiSig ProposalDetail (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    fn approve_as_key() -> Weight {
        // Minimum execution time: 22_712 nanoseconds.
        Weight::from_ref_time(23_234_000)
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(4))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSigners (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig ProposalDetail (r:1 w:1)
    // Proof Skipped: MultiSig ProposalDetail (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Votes (r:1 w:1)
    // Proof Skipped: MultiSig Votes (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig NumberOfSigners (r:1 w:0)
    // Proof Skipped: MultiSig NumberOfSigners (max_values: None, max_size: None, mode: Measured)
    fn reject_as_identity() -> Weight {
        // Minimum execution time: 21_941 nanoseconds.
        Weight::from_ref_time(22_743_000)
            .saturating_add(DbWeight::get().reads(7))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: MultiSig MultiSigSigners (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig ProposalDetail (r:1 w:1)
    // Proof Skipped: MultiSig ProposalDetail (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Votes (r:1 w:1)
    // Proof Skipped: MultiSig Votes (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig NumberOfSigners (r:1 w:0)
    // Proof Skipped: MultiSig NumberOfSigners (max_values: None, max_size: None, mode: Measured)
    fn reject_as_key() -> Weight {
        // Minimum execution time: 18_214 nanoseconds.
        Weight::from_ref_time(18_585_000)
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: Identity Authorizations (r:1 w:1)
    // Proof Skipped: Identity Authorizations (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity OutdatedAuthorizations (r:1 w:0)
    // Proof Skipped: Identity OutdatedAuthorizations (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CddAuthForPrimaryKeyRotation (r:1 w:0)
    // Proof Skipped: Identity CddAuthForPrimaryKeyRotation (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSigners (r:1 w:1)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1 w:1)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig NumberOfSigners (r:1 w:1)
    // Proof Skipped: MultiSig NumberOfSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity NumberOfGivenAuths (r:1 w:1)
    // Proof Skipped: Identity NumberOfGivenAuths (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity AuthorizationsGiven (r:0 w:1)
    // Proof Skipped: Identity AuthorizationsGiven (max_values: None, max_size: None, mode: Measured)
    fn accept_multisig_signer_as_key() -> Weight {
        // Minimum execution time: 23_304 nanoseconds.
        Weight::from_ref_time(23_584_000)
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(6))
    }
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity NumberOfGivenAuths (r:1 w:1)
    // Proof Skipped: Identity NumberOfGivenAuths (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CurrentAuthId (r:1 w:1)
    // Proof Skipped: Identity CurrentAuthId (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity AuthorizationsGiven (r:0 w:1)
    // Proof Skipped: Identity AuthorizationsGiven (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity Authorizations (r:0 w:1)
    // Proof Skipped: Identity Authorizations (max_values: None, max_size: None, mode: Measured)
    fn add_multisig_signer() -> Weight {
        // Minimum execution time: 13_936 nanoseconds.
        Weight::from_ref_time(14_187_000)
            .saturating_add(DbWeight::get().reads(3))
            .saturating_add(DbWeight::get().writes(4))
    }
    fn accept_multisig_signer_as_identity() -> Weight {
        // Minimum execution time: 126_016 nanoseconds.
        Weight::from_ref_time(139_000_000)
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().writes(4))
    }
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSigners (r:1 w:1)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig NumberOfSigners (r:1 w:1)
    // Proof Skipped: MultiSig NumberOfSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CddAuthForPrimaryKeyRotation (r:1 w:0)
    // Proof Skipped: Identity CddAuthForPrimaryKeyRotation (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    fn remove_multisig_signer() -> Weight {
        // Minimum execution time: 16_370 nanoseconds.
        Weight::from_ref_time(16_851_000)
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:1 w:0)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig LostCreatorPrivileges (r:1 w:0)
    // Proof Skipped: MultiSig LostCreatorPrivileges (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity NumberOfGivenAuths (r:1 w:1)
    // Proof Skipped: Identity NumberOfGivenAuths (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CurrentAuthId (r:1 w:1)
    // Proof Skipped: Identity CurrentAuthId (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity AuthorizationsGiven (r:0 w:256)
    // Proof Skipped: Identity AuthorizationsGiven (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity Authorizations (r:0 w:256)
    // Proof Skipped: Identity Authorizations (max_values: None, max_size: None, mode: Measured)
    /// The range of component `i` is `[1, 256]`.
    fn add_multisig_signers_via_creator(i: u32) -> Weight {
        // Minimum execution time: 20_538 nanoseconds.
        Weight::from_ref_time(10_059_252)
            // Standard Error: 11_896
            .saturating_add(Weight::from_ref_time(4_655_768).saturating_mul(i.into()))
            .saturating_add(DbWeight::get().reads(7))
            .saturating_add(DbWeight::get().writes(2))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(i.into())))
    }
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:257 w:256)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:1 w:0)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig LostCreatorPrivileges (r:1 w:0)
    // Proof Skipped: MultiSig LostCreatorPrivileges (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CddAuthForPrimaryKeyRotation (r:1 w:0)
    // Proof Skipped: Identity CddAuthForPrimaryKeyRotation (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: MultiSig NumberOfSigners (r:1 w:1)
    // Proof Skipped: MultiSig NumberOfSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSignsRequired (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSigners (r:256 w:256)
    // Proof Skipped: MultiSig MultiSigSigners (max_values: None, max_size: None, mode: Measured)
    /// The range of component `i` is `[1, 256]`.
    fn remove_multisig_signers_via_creator(i: u32) -> Weight {
        // Minimum execution time: 24_025 nanoseconds.
        Weight::from_ref_time(24_997_000)
            // Standard Error: 10_933
            .saturating_add(Weight::from_ref_time(5_902_746).saturating_mul(i.into()))
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().reads((2_u64).saturating_mul(i.into())))
            .saturating_add(DbWeight::get().writes(1))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(i.into())))
    }
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig NumberOfSigners (r:1 w:0)
    // Proof Skipped: MultiSig NumberOfSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CddAuthForPrimaryKeyRotation (r:1 w:0)
    // Proof Skipped: Identity CddAuthForPrimaryKeyRotation (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSignsRequired (r:0 w:1)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    fn change_sigs_required() -> Weight {
        // Minimum execution time: 12_313 nanoseconds.
        Weight::from_ref_time(12_594_000)
            .saturating_add(DbWeight::get().reads(4))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Identity KeyRecords (r:2 w:1)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidKeys (r:0 w:1)
    // Proof Skipped: Identity DidKeys (max_values: None, max_size: None, mode: Measured)
    fn make_multisig_secondary() -> Weight {
        // Minimum execution time: 14_177 nanoseconds.
        Weight::from_ref_time(14_567_000)
            .saturating_add(DbWeight::get().reads(3))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:2 w:2)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:2 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:1 w:1)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity AccountKeyRefCount (r:1 w:0)
    // Proof Skipped: Identity AccountKeyRefCount (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CddAuthForPrimaryKeyRotation (r:1 w:0)
    // Proof Skipped: Identity CddAuthForPrimaryKeyRotation (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity DidKeys (r:0 w:2)
    // Proof Skipped: Identity DidKeys (max_values: None, max_size: None, mode: Measured)
    fn make_multisig_primary() -> Weight {
        // Minimum execution time: 20_398 nanoseconds.
        Weight::from_ref_time(20_679_000)
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(5))
    }
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Instance2Group ActiveMembers (r:1 w:0)
    // Proof Skipped: Instance2Group ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:2 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:1 w:0)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig Proposals (r:1 w:0)
    // Proof Skipped: MultiSig Proposals (max_values: None, max_size: None, mode: Measured)
    // Storage: Permissions CurrentPalletName (r:1 w:1)
    // Proof Skipped: Permissions CurrentPalletName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Permissions CurrentDispatchableName (r:1 w:1)
    // Proof Skipped: Permissions CurrentDispatchableName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: MultiSig ProposalDetail (r:1 w:1)
    // Proof Skipped: MultiSig ProposalDetail (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CurrentDid (r:0 w:1)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity CurrentPayer (r:0 w:1)
    // Proof Skipped: Identity CurrentPayer (max_values: Some(1), max_size: None, mode: Measured)
    fn execute_scheduled_proposal() -> Weight {
        // Minimum execution time: 28_353 nanoseconds.
        Weight::from_ref_time(29_024_000)
            .saturating_add(DbWeight::get().reads(9))
            .saturating_add(DbWeight::get().writes(5))
    }
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:1 w:0)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig LostCreatorPrivileges (r:1 w:0)
    // Proof Skipped: MultiSig LostCreatorPrivileges (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig NumberOfSigners (r:1 w:0)
    // Proof Skipped: MultiSig NumberOfSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity CddAuthForPrimaryKeyRotation (r:1 w:0)
    // Proof Skipped: Identity CddAuthForPrimaryKeyRotation (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigSignsRequired (r:0 w:1)
    // Proof Skipped: MultiSig MultiSigSignsRequired (max_values: None, max_size: None, mode: Measured)
    fn change_sigs_required_via_creator() -> Weight {
        // Minimum execution time: 19_407 nanoseconds.
        Weight::from_ref_time(19_717_000)
            .saturating_add(DbWeight::get().reads(7))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Identity CurrentDid (r:1 w:0)
    // Proof Skipped: Identity CurrentDid (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig MultiSigToIdentity (r:1 w:0)
    // Proof Skipped: MultiSig MultiSigToIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:1 w:0)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: MultiSig LostCreatorPrivileges (r:0 w:1)
    // Proof Skipped: MultiSig LostCreatorPrivileges (max_values: None, max_size: None, mode: Measured)
    fn remove_creator_controls() -> Weight {
        // Minimum execution time: 12_223 nanoseconds.
        Weight::from_ref_time(12_674_000)
            .saturating_add(DbWeight::get().reads(4))
            .saturating_add(DbWeight::get().writes(1))
    }
}
