// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_settlement
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-11-05, STEPS: `100`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 512
//! HOSTNAME: `Ubuntu-2204-jammy-amd64-base`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`

// Executed Command:
// ./polymesh-private
// benchmark
// pallet
// -s
// 100
// -r
// 5
// -p=*
// -e=*
// --heap-pages
// 4096
// --db-cache
// 512
// --execution
// wasm
// --wasm-execution
// compiled
// --output
// ./Polymesh-private/pallets/weights/src/
// --template
// ./Polymesh-private/.maintain/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use polymesh_runtime_common::{RocksDbWeight as DbWeight, Weight};

/// Weights for pallet_settlement using the Substrate node and recommended hardware.
pub struct SubstrateWeight;
impl pallet_settlement::WeightInfo for SubstrateWeight {
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueCounter (r:1 w:1)
    // Proof Skipped: Settlement VenueCounter (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Settlement VenueInfo (r:0 w:1)
    // Proof Skipped: Settlement VenueInfo (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement Details (r:0 w:1)
    // Proof Skipped: Settlement Details (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement NumberOfVenueSigners (r:0 w:1)
    // Proof Skipped: Settlement NumberOfVenueSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueSigners (r:0 w:49)
    // Proof Skipped: Settlement VenueSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserVenues (r:0 w:1)
    // Proof Skipped: Settlement UserVenues (max_values: None, max_size: None, mode: Measured)
    /// The range of component `d` is `[1, 2048]`.
    /// The range of component `s` is `[0, 50]`.
    fn create_venue(d: u32, s: u32) -> Weight {
        // Minimum execution time: 26_890 nanoseconds.
        Weight::from_ref_time(33_796_190)
            // Standard Error: 1_519
            .saturating_add(Weight::from_ref_time(5_390).saturating_mul(d.into()))
            // Standard Error: 11_164
            .saturating_add(Weight::from_ref_time(1_647_581).saturating_mul(s.into()))
            .saturating_add(DbWeight::get().reads(2))
            .saturating_add(DbWeight::get().writes(5))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(s.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInfo (r:1 w:0)
    // Proof Skipped: Settlement VenueInfo (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement Details (r:0 w:1)
    // Proof Skipped: Settlement Details (max_values: None, max_size: None, mode: Measured)
    /// The range of component `d` is `[1, 2048]`.
    fn update_venue_details(d: u32) -> Weight {
        // Minimum execution time: 20_278 nanoseconds.
        Weight::from_ref_time(22_686_727)
            // Standard Error: 102
            .saturating_add(Weight::from_ref_time(1_227).saturating_mul(d.into()))
            .saturating_add(DbWeight::get().reads(2))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInfo (r:1 w:1)
    // Proof Skipped: Settlement VenueInfo (max_values: None, max_size: None, mode: Measured)
    fn update_venue_type() -> Weight {
        // Minimum execution time: 19_827 nanoseconds.
        Weight::from_ref_time(20_118_000)
            .saturating_add(DbWeight::get().reads(2))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInfo (r:1 w:0)
    // Proof Skipped: Settlement VenueInfo (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement NumberOfVenueSigners (r:1 w:1)
    // Proof Skipped: Settlement NumberOfVenueSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueSigners (r:49 w:49)
    // Proof Skipped: Settlement VenueSigners (max_values: None, max_size: None, mode: Measured)
    /// The range of component `s` is `[0, 50]`.
    fn update_venue_signers(s: u32) -> Weight {
        // Minimum execution time: 20_419 nanoseconds.
        Weight::from_ref_time(29_114_162)
            // Standard Error: 18_042
            .saturating_add(Weight::from_ref_time(3_230_036).saturating_mul(s.into()))
            .saturating_add(DbWeight::get().reads(3))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(s.into())))
            .saturating_add(DbWeight::get().writes(1))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(s.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: ExternalAgents GroupOfAgent (r:1 w:0)
    // Proof Skipped: ExternalAgents GroupOfAgent (max_values: None, max_size: None, mode: Measured)
    // Storage: Permissions CurrentPalletName (r:1 w:0)
    // Proof Skipped: Permissions CurrentPalletName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Permissions CurrentDispatchableName (r:1 w:0)
    // Proof Skipped: Permissions CurrentDispatchableName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Settlement VenueFiltering (r:0 w:1)
    // Proof Skipped: Settlement VenueFiltering (max_values: None, max_size: None, mode: Measured)
    fn set_venue_filtering() -> Weight {
        // Minimum execution time: 21_931 nanoseconds.
        Weight::from_ref_time(22_392_000)
            .saturating_add(DbWeight::get().reads(4))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: ExternalAgents GroupOfAgent (r:1 w:0)
    // Proof Skipped: ExternalAgents GroupOfAgent (max_values: None, max_size: None, mode: Measured)
    // Storage: Permissions CurrentPalletName (r:1 w:0)
    // Proof Skipped: Permissions CurrentPalletName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Permissions CurrentDispatchableName (r:1 w:0)
    // Proof Skipped: Permissions CurrentDispatchableName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Settlement VenueAllowList (r:0 w:99)
    // Proof Skipped: Settlement VenueAllowList (max_values: None, max_size: None, mode: Measured)
    /// The range of component `v` is `[0, 100]`.
    fn allow_venues(v: u32) -> Weight {
        // Minimum execution time: 20_258 nanoseconds.
        Weight::from_ref_time(21_053_430)
            // Standard Error: 38_347
            .saturating_add(Weight::from_ref_time(1_826_136).saturating_mul(v.into()))
            .saturating_add(DbWeight::get().reads(4))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(v.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: ExternalAgents GroupOfAgent (r:1 w:0)
    // Proof Skipped: ExternalAgents GroupOfAgent (max_values: None, max_size: None, mode: Measured)
    // Storage: Permissions CurrentPalletName (r:1 w:0)
    // Proof Skipped: Permissions CurrentPalletName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Permissions CurrentDispatchableName (r:1 w:0)
    // Proof Skipped: Permissions CurrentDispatchableName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Settlement VenueAllowList (r:0 w:99)
    // Proof Skipped: Settlement VenueAllowList (max_values: None, max_size: None, mode: Measured)
    /// The range of component `v` is `[0, 100]`.
    fn disallow_venues(v: u32) -> Weight {
        // Minimum execution time: 19_747 nanoseconds.
        Weight::from_ref_time(18_741_446)
            // Standard Error: 41_151
            .saturating_add(Weight::from_ref_time(1_836_394).saturating_mul(v.into()))
            .saturating_add(DbWeight::get().reads(4))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(v.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:0)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:0)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:110 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:110 w:110)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueSigners (r:1 w:0)
    // Proof Skipped: Settlement VenueSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement ReceiptsUsed (r:10 w:10)
    // Proof Skipped: Settlement ReceiptsUsed (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:0)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:10 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioNFT (r:100 w:0)
    // Proof Skipped: Portfolio PortfolioNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:10 w:0)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetBalances (r:10 w:0)
    // Proof Skipped: Portfolio PortfolioAssetBalances (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:110)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:0 w:120)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn affirm_with_receipts(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 937_999 nanoseconds.
        Weight::from_ref_time(939_523_000)
            // Standard Error: 121_371
            .saturating_add(Weight::from_ref_time(20_654_681).saturating_mul(n.into()))
            // Standard Error: 1_209_138
            .saturating_add(Weight::from_ref_time(27_034_852).saturating_mul(o.into()))
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().reads((6_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((5_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(1))
            .saturating_add(DbWeight::get().writes((4_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((4_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(o.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:1)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:1)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:120)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInfo (r:1 w:0)
    // Proof Skipped: Settlement VenueInfo (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Settlement InstructionMediatorsAffirmations (r:445 w:444)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:10 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:220 w:220)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:220 w:220)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueFiltering (r:110 w:0)
    // Proof Skipped: Settlement VenueFiltering (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:120 w:120)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMemos (r:1 w:0)
    // Proof Skipped: Settlement InstructionMemos (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:10 w:0)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset BalanceOf (r:20 w:20)
    // Proof Skipped: Asset BalanceOf (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio Portfolios (r:20 w:0)
    // Proof Skipped: Portfolio Portfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetBalances (r:20 w:20)
    // Proof Skipped: Portfolio PortfolioAssetBalances (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Frozen (r:110 w:0)
    // Proof Skipped: Asset Frozen (max_values: None, max_size: None, mode: Measured)
    // Storage: Instance2Group ActiveMembers (r:1 w:0)
    // Proof Skipped: Instance2Group ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:205 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: Statistics AssetTransferCompliances (r:10 w:0)
    // Proof Skipped: Statistics AssetTransferCompliances (max_values: None, max_size: None, mode: Measured)
    // Storage: Statistics AssetStats (r:140 w:100)
    // Proof Skipped: Statistics AssetStats (max_values: None, max_size: None, mode: Measured)
    // Storage: ComplianceManager AssetCompliances (r:110 w:0)
    // Proof Skipped: ComplianceManager AssetCompliances (max_values: None, max_size: None, mode: Measured)
    // Storage: Checkpoint CachedNextCheckpoints (r:10 w:0)
    // Proof Skipped: Checkpoint CachedNextCheckpoints (max_values: None, max_size: None, mode: Measured)
    // Storage: Checkpoint CheckpointIdSequence (r:10 w:0)
    // Proof Skipped: Checkpoint CheckpointIdSequence (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetCount (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioAssetCount (max_values: None, max_size: None, mode: Measured)
    // Storage: Statistics ActiveAssetStats (r:10 w:0)
    // Proof Skipped: Statistics ActiveAssetStats (max_values: None, max_size: None, mode: Measured)
    // Storage: NFT CollectionAsset (r:100 w:0)
    // Proof Skipped: NFT CollectionAsset (max_values: None, max_size: None, mode: Measured)
    // Storage: NFT NumberOfNFTs (r:200 w:200)
    // Proof Skipped: NFT NumberOfNFTs (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioNFT (r:100 w:200)
    // Proof Skipped: Portfolio PortfolioNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: NFT NFTOwner (r:0 w:100)
    // Proof Skipped: NFT NFTOwner (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInstructions (r:0 w:1)
    // Proof Skipped: Settlement VenueInstructions (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn execute_manual_instruction(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 2_816_364 nanoseconds.
        Weight::from_ref_time(114_493_120)
            // Standard Error: 6_986_977
            .saturating_add(Weight::from_ref_time(369_189_962).saturating_mul(f.into()))
            // Standard Error: 646_314
            .saturating_add(Weight::from_ref_time(130_250_468).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(19))
            .saturating_add(DbWeight::get().reads((60_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((18_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(8))
            .saturating_add(DbWeight::get().writes((26_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((16_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(o.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInfo (r:1 w:0)
    // Proof Skipped: Settlement VenueInfo (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:110 w:0)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueFiltering (r:110 w:0)
    // Proof Skipped: Settlement VenueFiltering (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:2 w:0)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio Portfolios (r:220 w:0)
    // Proof Skipped: Portfolio Portfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:110 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset AssetsExemptFromAffirmation (r:110 w:0)
    // Proof Skipped: Asset AssetsExemptFromAffirmation (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset PreApprovedAsset (r:110 w:0)
    // Proof Skipped: Asset PreApprovedAsset (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PreApprovedPortfolios (r:110 w:0)
    // Proof Skipped: Portfolio PreApprovedPortfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset MandatoryMediators (r:110 w:0)
    // Proof Skipped: Asset MandatoryMediators (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionCounter (r:1 w:1)
    // Proof Skipped: Settlement InstructionCounter (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: Settlement InstructionLegs (r:0 w:120)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:0 w:220)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:0 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:0 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMemos (r:0 w:1)
    // Proof Skipped: Settlement InstructionMemos (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:0 w:1)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:0 w:1)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInstructions (r:0 w:1)
    // Proof Skipped: Settlement VenueInstructions (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMediatorsAffirmations (r:0 w:440)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn add_instruction(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 419_427 nanoseconds.
        Weight::from_ref_time(326_940_968)
            // Standard Error: 1_694_613
            .saturating_add(Weight::from_ref_time(22_503_140).saturating_mul(f.into()))
            // Standard Error: 156_756
            .saturating_add(Weight::from_ref_time(34_947_168).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().reads((9_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((9_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(8))
            .saturating_add(DbWeight::get().writes((7_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((7_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(o.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInfo (r:1 w:0)
    // Proof Skipped: Settlement VenueInfo (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:110 w:0)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueFiltering (r:110 w:0)
    // Proof Skipped: Settlement VenueFiltering (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:2 w:0)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio Portfolios (r:220 w:0)
    // Proof Skipped: Portfolio Portfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:220 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset AssetsExemptFromAffirmation (r:110 w:0)
    // Proof Skipped: Asset AssetsExemptFromAffirmation (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset PreApprovedAsset (r:110 w:0)
    // Proof Skipped: Asset PreApprovedAsset (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PreApprovedPortfolios (r:110 w:0)
    // Proof Skipped: Portfolio PreApprovedPortfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset MandatoryMediators (r:110 w:0)
    // Proof Skipped: Asset MandatoryMediators (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionCounter (r:1 w:1)
    // Proof Skipped: Settlement InstructionCounter (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: Settlement InstructionLegs (r:121 w:120)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioNFT (r:100 w:0)
    // Proof Skipped: Portfolio PortfolioNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetBalances (r:10 w:0)
    // Proof Skipped: Portfolio PortfolioAssetBalances (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:0 w:220)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:0 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:0 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMemos (r:0 w:1)
    // Proof Skipped: Settlement InstructionMemos (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:0 w:1)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:0 w:1)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInstructions (r:0 w:1)
    // Proof Skipped: Settlement VenueInstructions (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMediatorsAffirmations (r:0 w:440)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:110)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:0 w:110)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn add_and_affirm_instruction(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 752_802 nanoseconds.
        Weight::from_ref_time(754_816_000)
            // Standard Error: 1_899_269
            .saturating_add(Weight::from_ref_time(10_878_533).saturating_mul(f.into()))
            // Standard Error: 183_387
            .saturating_add(Weight::from_ref_time(55_588_436).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(9))
            .saturating_add(DbWeight::get().reads((13_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((13_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(8))
            .saturating_add(DbWeight::get().writes((10_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((10_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(o.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:0)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:0)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:110 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:110 w:110)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:0)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioNFT (r:100 w:0)
    // Proof Skipped: Portfolio PortfolioNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:10 w:0)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetBalances (r:10 w:0)
    // Proof Skipped: Portfolio PortfolioAssetBalances (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:110)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:0 w:110)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[1, 100]`.
    fn affirm_instruction(f: u32, n: u32) -> Weight {
        // Minimum execution time: 390_492 nanoseconds.
        Weight::from_ref_time(87_889_880)
            // Standard Error: 1_502_157
            .saturating_add(Weight::from_ref_time(25_253_651).saturating_mul(f.into()))
            // Standard Error: 141_154
            .saturating_add(Weight::from_ref_time(24_372_512).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(15))
            .saturating_add(DbWeight::get().reads((6_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((5_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(1))
            .saturating_add(DbWeight::get().writes((4_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((4_u64).saturating_mul(n.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:0)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:0)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:110 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:110 w:110)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:0)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:110 w:110)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:110)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn withdraw_affirmation(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 298_830 nanoseconds.
        Weight::from_ref_time(176_131_987)
            // Standard Error: 1_021_889
            .saturating_add(Weight::from_ref_time(22_609_390).saturating_mul(f.into()))
            // Standard Error: 94_527
            .saturating_add(Weight::from_ref_time(25_190_824).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(5))
            .saturating_add(DbWeight::get().reads((5_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((5_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(1))
            .saturating_add(DbWeight::get().writes((4_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((4_u64).saturating_mul(n.into())))
    }
    // Storage: Settlement InstructionStatuses (r:1 w:1)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:120)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:1 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:120 w:120)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: Settlement InstructionDetails (r:1 w:1)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMediatorsAffirmations (r:5 w:4)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:0 w:220)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:0 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:0 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInstructions (r:0 w:1)
    // Proof Skipped: Settlement VenueInstructions (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:220)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn reject_instruction(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 376_576 nanoseconds.
        Weight::from_ref_time(360_713_701)
            // Standard Error: 91_669
            .saturating_add(Weight::from_ref_time(23_492_499).saturating_mul(n.into()))
            // Standard Error: 897_687
            .saturating_add(Weight::from_ref_time(5_986_226).saturating_mul(o.into()))
            .saturating_add(DbWeight::get().reads(12))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((2_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(10))
            .saturating_add(DbWeight::get().writes((7_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((7_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(o.into())))
    }
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:1)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Settlement InstructionMediatorsAffirmations (r:445 w:444)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:120)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:10 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:220 w:220)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:220 w:220)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:1)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueFiltering (r:110 w:0)
    // Proof Skipped: Settlement VenueFiltering (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:120 w:120)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMemos (r:1 w:0)
    // Proof Skipped: Settlement InstructionMemos (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:10 w:0)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset BalanceOf (r:20 w:20)
    // Proof Skipped: Asset BalanceOf (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio Portfolios (r:20 w:0)
    // Proof Skipped: Portfolio Portfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetBalances (r:20 w:20)
    // Proof Skipped: Portfolio PortfolioAssetBalances (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Frozen (r:110 w:0)
    // Proof Skipped: Asset Frozen (max_values: None, max_size: None, mode: Measured)
    // Storage: Instance2Group ActiveMembers (r:1 w:0)
    // Proof Skipped: Instance2Group ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:4 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: Statistics AssetTransferCompliances (r:10 w:0)
    // Proof Skipped: Statistics AssetTransferCompliances (max_values: None, max_size: None, mode: Measured)
    // Storage: ComplianceManager AssetCompliances (r:110 w:0)
    // Proof Skipped: ComplianceManager AssetCompliances (max_values: None, max_size: None, mode: Measured)
    // Storage: Checkpoint CachedNextCheckpoints (r:10 w:0)
    // Proof Skipped: Checkpoint CachedNextCheckpoints (max_values: None, max_size: None, mode: Measured)
    // Storage: Checkpoint CheckpointIdSequence (r:10 w:0)
    // Proof Skipped: Checkpoint CheckpointIdSequence (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetCount (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioAssetCount (max_values: None, max_size: None, mode: Measured)
    // Storage: Statistics ActiveAssetStats (r:10 w:0)
    // Proof Skipped: Statistics ActiveAssetStats (max_values: None, max_size: None, mode: Measured)
    // Storage: NFT CollectionAsset (r:100 w:0)
    // Proof Skipped: NFT CollectionAsset (max_values: None, max_size: None, mode: Measured)
    // Storage: NFT NumberOfNFTs (r:200 w:200)
    // Proof Skipped: NFT NumberOfNFTs (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioNFT (r:100 w:200)
    // Proof Skipped: Portfolio PortfolioNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: NFT NFTOwner (r:0 w:100)
    // Proof Skipped: NFT NFTOwner (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInstructions (r:0 w:1)
    // Proof Skipped: Settlement VenueInstructions (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn execute_instruction_paused(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 1_652_450 nanoseconds.
        Weight::from_ref_time(1_659_273_000)
            // Standard Error: 4_671_623
            .saturating_add(Weight::from_ref_time(64_034_851).saturating_mul(f.into()))
            // Standard Error: 451_077
            .saturating_add(Weight::from_ref_time(121_714_587).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(16))
            .saturating_add(DbWeight::get().reads((26_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((18_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(8))
            .saturating_add(DbWeight::get().writes((16_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((16_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(o.into())))
    }
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:1)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Settlement InstructionMediatorsAffirmations (r:445 w:444)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:120)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:10 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:220 w:220)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:220 w:220)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:1)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueFiltering (r:110 w:0)
    // Proof Skipped: Settlement VenueFiltering (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:120 w:120)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMemos (r:1 w:0)
    // Proof Skipped: Settlement InstructionMemos (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:10 w:0)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset BalanceOf (r:20 w:20)
    // Proof Skipped: Asset BalanceOf (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio Portfolios (r:20 w:0)
    // Proof Skipped: Portfolio Portfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetBalances (r:20 w:20)
    // Proof Skipped: Portfolio PortfolioAssetBalances (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Frozen (r:110 w:0)
    // Proof Skipped: Asset Frozen (max_values: None, max_size: None, mode: Measured)
    // Storage: Instance2Group ActiveMembers (r:1 w:0)
    // Proof Skipped: Instance2Group ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:205 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: Statistics AssetTransferCompliances (r:10 w:0)
    // Proof Skipped: Statistics AssetTransferCompliances (max_values: None, max_size: None, mode: Measured)
    // Storage: Statistics AssetStats (r:140 w:100)
    // Proof Skipped: Statistics AssetStats (max_values: None, max_size: None, mode: Measured)
    // Storage: ComplianceManager AssetCompliances (r:110 w:0)
    // Proof Skipped: ComplianceManager AssetCompliances (max_values: None, max_size: None, mode: Measured)
    // Storage: Checkpoint CachedNextCheckpoints (r:10 w:0)
    // Proof Skipped: Checkpoint CachedNextCheckpoints (max_values: None, max_size: None, mode: Measured)
    // Storage: Checkpoint CheckpointIdSequence (r:10 w:0)
    // Proof Skipped: Checkpoint CheckpointIdSequence (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetCount (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioAssetCount (max_values: None, max_size: None, mode: Measured)
    // Storage: Statistics ActiveAssetStats (r:10 w:0)
    // Proof Skipped: Statistics ActiveAssetStats (max_values: None, max_size: None, mode: Measured)
    // Storage: NFT CollectionAsset (r:100 w:0)
    // Proof Skipped: NFT CollectionAsset (max_values: None, max_size: None, mode: Measured)
    // Storage: NFT NumberOfNFTs (r:200 w:200)
    // Proof Skipped: NFT NumberOfNFTs (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioNFT (r:100 w:200)
    // Proof Skipped: Portfolio PortfolioNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: NFT NFTOwner (r:0 w:100)
    // Proof Skipped: NFT NFTOwner (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInstructions (r:0 w:1)
    // Proof Skipped: Settlement VenueInstructions (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn execute_scheduled_instruction(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 2_921_270 nanoseconds.
        Weight::from_ref_time(147_376_717)
            // Standard Error: 5_771_414
            .saturating_add(Weight::from_ref_time(171_290_749).saturating_mul(f.into()))
            // Standard Error: 533_871
            .saturating_add(Weight::from_ref_time(130_266_277).saturating_mul(n.into()))
            // Standard Error: 5_228_009
            .saturating_add(Weight::from_ref_time(66_807_012).saturating_mul(o.into()))
            .saturating_add(DbWeight::get().reads(17))
            .saturating_add(DbWeight::get().reads((60_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((18_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(8))
            .saturating_add(DbWeight::get().writes((26_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((16_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(o.into())))
    }
    fn ensure_root_origin() -> Weight {
        // Minimum execution time: 491 nanoseconds.
        Weight::from_ref_time(521_000)
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:0)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:0)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:110 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:110 w:110)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueSigners (r:1 w:0)
    // Proof Skipped: Settlement VenueSigners (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement ReceiptsUsed (r:10 w:10)
    // Proof Skipped: Settlement ReceiptsUsed (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:0)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:10 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:110)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:0 w:10)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn affirm_with_receipts_rcv(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 748_465 nanoseconds.
        Weight::from_ref_time(33_233_141)
            // Standard Error: 986_276
            .saturating_add(Weight::from_ref_time(16_132_355).saturating_mul(f.into()))
            // Standard Error: 91_233
            .saturating_add(Weight::from_ref_time(15_757_159).saturating_mul(n.into()))
            // Standard Error: 893_414
            .saturating_add(Weight::from_ref_time(51_815_722).saturating_mul(o.into()))
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(1))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(o.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:0)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:0)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:110 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:110 w:110)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:0)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:110)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[1, 100]`.
    fn affirm_instruction_rcv(f: u32, n: u32) -> Weight {
        // Minimum execution time: 244_258 nanoseconds.
        Weight::from_ref_time(194_479_061)
            // Standard Error: 728_961
            .saturating_add(Weight::from_ref_time(3_302_420).saturating_mul(f.into()))
            // Standard Error: 68_498
            .saturating_add(Weight::from_ref_time(14_388_864).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(15))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(1))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(n.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:0)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:0)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:110 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:110 w:110)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:0)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:110)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn withdraw_affirmation_rcv(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 205_796 nanoseconds.
        Weight::from_ref_time(206_557_000)
            // Standard Error: 390_469
            .saturating_add(Weight::from_ref_time(19_580_333).saturating_mul(f.into()))
            // Standard Error: 37_702
            .saturating_add(Weight::from_ref_time(13_428_283).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(5))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(1))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(n.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInfo (r:1 w:0)
    // Proof Skipped: Settlement VenueInfo (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:110 w:0)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueFiltering (r:110 w:0)
    // Proof Skipped: Settlement VenueFiltering (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:2 w:0)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio Portfolios (r:220 w:0)
    // Proof Skipped: Portfolio Portfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:110 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset AssetsExemptFromAffirmation (r:110 w:0)
    // Proof Skipped: Asset AssetsExemptFromAffirmation (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset PreApprovedAsset (r:110 w:0)
    // Proof Skipped: Asset PreApprovedAsset (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PreApprovedPortfolios (r:110 w:0)
    // Proof Skipped: Portfolio PreApprovedPortfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset MandatoryMediators (r:110 w:0)
    // Proof Skipped: Asset MandatoryMediators (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionCounter (r:1 w:1)
    // Proof Skipped: Settlement InstructionCounter (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: Settlement InstructionLegs (r:0 w:120)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:0 w:220)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:0 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:0 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMemos (r:0 w:1)
    // Proof Skipped: Settlement InstructionMemos (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:0 w:1)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:0 w:1)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInstructions (r:0 w:1)
    // Proof Skipped: Settlement VenueInstructions (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMediatorsAffirmations (r:0 w:444)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    /// The range of component `m` is `[0, 4]`.
    fn add_instruction_with_mediators(f: u32, n: u32, o: u32, m: u32) -> Weight {
        // Minimum execution time: 470_343 nanoseconds.
        Weight::from_ref_time(13_439_685)
            // Standard Error: 1_533_262
            .saturating_add(Weight::from_ref_time(25_726_838).saturating_mul(f.into()))
            // Standard Error: 141_488
            .saturating_add(Weight::from_ref_time(33_732_690).saturating_mul(n.into()))
            // Standard Error: 1_389_351
            .saturating_add(Weight::from_ref_time(8_445_816).saturating_mul(o.into()))
            // Standard Error: 3_217_219
            .saturating_add(Weight::from_ref_time(40_608_934).saturating_mul(m.into()))
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().reads((9_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((9_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(8))
            .saturating_add(DbWeight::get().writes((7_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((7_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(m.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInfo (r:1 w:0)
    // Proof Skipped: Settlement VenueInfo (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:110 w:0)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueFiltering (r:110 w:0)
    // Proof Skipped: Settlement VenueFiltering (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity DidRecords (r:2 w:0)
    // Proof Skipped: Identity DidRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio Portfolios (r:220 w:0)
    // Proof Skipped: Portfolio Portfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:220 w:0)
    // Proof Skipped: Portfolio PortfolioCustodian (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset AssetsExemptFromAffirmation (r:110 w:0)
    // Proof Skipped: Asset AssetsExemptFromAffirmation (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset PreApprovedAsset (r:110 w:0)
    // Proof Skipped: Asset PreApprovedAsset (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PreApprovedPortfolios (r:110 w:0)
    // Proof Skipped: Portfolio PreApprovedPortfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset MandatoryMediators (r:110 w:0)
    // Proof Skipped: Asset MandatoryMediators (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionCounter (r:1 w:1)
    // Proof Skipped: Settlement InstructionCounter (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: Settlement InstructionLegs (r:121 w:120)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioNFT (r:100 w:0)
    // Proof Skipped: Portfolio PortfolioNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioAssetBalances (r:10 w:0)
    // Proof Skipped: Portfolio PortfolioAssetBalances (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:0 w:220)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:0 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:0 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMemos (r:0 w:1)
    // Proof Skipped: Settlement InstructionMemos (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:0 w:1)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:0 w:1)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInstructions (r:0 w:1)
    // Proof Skipped: Settlement VenueInstructions (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMediatorsAffirmations (r:0 w:444)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:110)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:0 w:110)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    /// The range of component `m` is `[0, 4]`.
    fn add_and_affirm_with_mediators(f: u32, n: u32, o: u32, m: u32) -> Weight {
        // Minimum execution time: 759_565 nanoseconds.
        Weight::from_ref_time(18_003_637)
            // Standard Error: 2_061_091
            .saturating_add(Weight::from_ref_time(69_464_479).saturating_mul(f.into()))
            // Standard Error: 190_195
            .saturating_add(Weight::from_ref_time(54_967_149).saturating_mul(n.into()))
            // Standard Error: 1_867_638
            .saturating_add(Weight::from_ref_time(4_637_535).saturating_mul(o.into()))
            // Standard Error: 4_324_753
            .saturating_add(Weight::from_ref_time(19_290_934).saturating_mul(m.into()))
            .saturating_add(DbWeight::get().reads(9))
            .saturating_add(DbWeight::get().reads((13_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((13_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(8))
            .saturating_add(DbWeight::get().writes((10_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((10_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(m.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:0)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:0)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMediatorsAffirmations (r:1 w:1)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    fn affirm_instruction_as_mediator() -> Weight {
        // Minimum execution time: 40_265 nanoseconds.
        Weight::from_ref_time(41_969_000)
            .saturating_add(DbWeight::get().reads(5))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionDetails (r:1 w:0)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionStatuses (r:1 w:0)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMediatorsAffirmations (r:1 w:1)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:1 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    fn withdraw_affirmation_as_mediator() -> Weight {
        // Minimum execution time: 38_853 nanoseconds.
        Weight::from_ref_time(39_244_000)
            .saturating_add(DbWeight::get().reads(5))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: Settlement InstructionStatuses (r:1 w:1)
    // Proof Skipped: Settlement InstructionStatuses (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegs (r:121 w:120)
    // Proof Skipped: Settlement InstructionLegs (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionMediatorsAffirmations (r:6 w:4)
    // Proof Skipped: Settlement InstructionMediatorsAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionLegStatus (r:120 w:120)
    // Proof Skipped: Settlement InstructionLegStatus (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedNFT (r:100 w:100)
    // Proof Skipped: Portfolio PortfolioLockedNFT (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioLockedAssets (r:10 w:10)
    // Proof Skipped: Portfolio PortfolioLockedAssets (max_values: None, max_size: None, mode: Measured)
    // Storage: Scheduler Lookup (r:1 w:1)
    // Proof: Scheduler Lookup (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Scheduler Agenda (r:1 w:1)
    // Proof: Scheduler Agenda (max_values: None, max_size: Some(10463), added: 12938, mode: MaxEncodedLen)
    // Storage: Settlement InstructionDetails (r:1 w:1)
    // Proof Skipped: Settlement InstructionDetails (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement UserAffirmations (r:0 w:220)
    // Proof Skipped: Settlement UserAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement OffChainAffirmations (r:0 w:10)
    // Proof Skipped: Settlement OffChainAffirmations (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement InstructionAffirmsPending (r:0 w:1)
    // Proof Skipped: Settlement InstructionAffirmsPending (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement VenueInstructions (r:0 w:1)
    // Proof Skipped: Settlement VenueInstructions (max_values: None, max_size: None, mode: Measured)
    // Storage: Settlement AffirmsReceived (r:0 w:220)
    // Proof Skipped: Settlement AffirmsReceived (max_values: None, max_size: None, mode: Measured)
    /// The range of component `f` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    /// The range of component `o` is `[0, 10]`.
    fn reject_instruction_as_mediator(f: u32, n: u32, o: u32) -> Weight {
        // Minimum execution time: 371_848 nanoseconds.
        Weight::from_ref_time(107_966_105)
            // Standard Error: 884_723
            .saturating_add(Weight::from_ref_time(13_501_420).saturating_mul(f.into()))
            // Standard Error: 81_839
            .saturating_add(Weight::from_ref_time(23_161_322).saturating_mul(n.into()))
            // Standard Error: 801_422
            .saturating_add(Weight::from_ref_time(9_536_297).saturating_mul(o.into()))
            .saturating_add(DbWeight::get().reads(12))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().reads((2_u64).saturating_mul(o.into())))
            .saturating_add(DbWeight::get().writes(10))
            .saturating_add(DbWeight::get().writes((7_u64).saturating_mul(f.into())))
            .saturating_add(DbWeight::get().writes((7_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(o.into())))
    }
}
